@startuml
!define LIGHTRED
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class User {
    +name: String[1]
    +createCampaign(): Campaign
    +createCharacter(): Character
    +joinParty(Invite)
}

note right of User::createCampaign
    Creates campaing and becomes DM
end note

class Campaign {
    +dungeonMaster: User[1]
    +name: String[1]
    +startScene(): Scene
    +addCharacter(Character)
    +deleteCharacter(Character)
}

class Invite {
    +url: URL[1]
    +addToCampaign(Character)
}

class Character {
    +name: String[1]
}

class Scene {
    +addAction(Action)
}

class Action {
    +text: String[1]
    +character: Character[1]
    +type: ActionType[1]
}

User "1" --> "0..*" Campaign : +campaigns
User "1" --> "0..*" Character : +characters

Campaign "1" <--> "1" Invite : +invite

Campaign "1" --> "0..*" Scene : +scenes
Campaign "1" --> "0..*" Character : +characters

Character "1..*" <--> "0..*" Scene : +scenes

User ..> Invite

Scene "1" --> "0..*" Action : actions

@enduml